[package]
name = "libp2p-test-muxer"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
edition = "2018"

[dependencies]
libp2p-core = { path = "../../core" }
log = "0.4"
env_logger = "0.6"
tokio = "0.1"
bytes = "0.4"
futures = "0.1"
assert_matches = "1.3"
rand = "0.6"
# TODO: uncomment this – using `extern crate` atm because IntelliJ is confused by new module system
#tcp  = { package = "libp2p-tcp-transport", path = "../../transports/tcp" }
libp2p-tcp-transport = { path = "../../transports/tcp" }
